### PR TITLE
Update to 0.6.13

### PR DESCRIPTION
**Pull request by Anthchirp**
and pull sources from pypi which should make the automatic update
checking bot happy.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Anthchirp** [comment]
@conda-forge-admin, please rerender

**Review by avrahamshukron — APPROVED** [review]

**Comment by Anthchirp** [comment]
_Okay kid, this is where it gets complicated._ - Amy Pond

We have a `cmake-format-feedstock` (this one) and a [`cmake_format-feedstock`](https://github.com/conda-forge/cmake_format-feedstock). The package itself was [recently renamed `cmake-format`→`cmakelang`](https://github.com/cheshirekow/cmake_format/blob/master/cmakelang/doc/installation.rst). There are pypi packages for both [`cmake-format`](https://pypi.org/project/cmake-format) and [`cmakelang`](https://pypi.org/project/cmakelang)

The pypi `cmake-format` old-name, transitional package is broken: It doesn't just declare a dependency on the new package and be done with it, instead it tries to download the sources and do the actual installation. However, it tries to download the sources from a Github repository that doesn't exist. This is why the build above fails.

After a quick chat with the conda-forces PTB this is my proposed solution:
* Keep this feedstock (`cmake-format-feedstock`)
* Archive the other feedstock ([`cmake_format-feedstock`](https://github.com/conda-forge/cmake_format-feedstock))
* Modify the recipe here to have 3 outputs:
  * `cmake-format`
  * `cmake_format`
  * `cmakelang`
* The first two outputs only add a pinned dependency on the third (`cmakelang`) and are otherwise empty. They only serve to keep the old names alive.
* The third output is the actual package, which will be derived from the [`cmakelang` pypi package](https://pypi.org/project/cmakelang)

**Comment by Anthchirp** [comment]
The source distribution and setup script have a number of problems. Reported upstream at cheshirekow/cmake_format#233 and cheshirekow/cmake_format#234. The definition of multiple packages in a single setup.py is causing the build failure here.

**Comment by xhochy** [comment]
If the new PyPI is now `cmakelang`, I would rather make a new feedstock and archive this one. This makes discoverability of the `feedstock` producing the package easier. Otherwise the plan sounds good and the bugs don't :(

**Comment by bdice** [comment]
I'm also interested in this. I tried `conda install -c conda-forge cmakelang` and was going to help create it if it didn't exist, which led me here. I agree with @xhochy's recommendation to archive this feedstock and create a new one for easier discoverability of the feedstock.

**Comment by bdice** [comment]
I opened a PR for a new recipe here and CI is passing. Only took 1.5 years. 🥳  https://github.com/conda-forge/staged-recipes/pull/18686

**Pull request closed without merging**
